config/routes.rb
Neighborhoodscms::Application.routes.draw do
  
  get "errors/not_found"

  match "/about_us" => "pages#about_us"
  match "/blog" => "pages#blog"
  match "/contact" => "pages#contact"
  match "/elements" => "pages#elements"
  match "/gallery" => "pages#gallery"
  match "/home_alternative" => "pages#home_alternative"
  match "/page_alternative" => "pages#page_alternative"
  match "/portfolio" => "pages#portfolio"
  match "/portfolio_item" => "pages#portfolio_item"
  match "/portfolio_item_2" => "pages#portfolio_item_2"
  match "/services" => "pages#services"
  match "/single_post" => "pages#single_post"
  match "/register" => "pages#register"

  match "/404" => "errors#not_found", as: "error_404"
  
  
  match "/:city" => "home#city"
  
  root :to => "home#index"

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name
  has_many :hoods
end

app/models/hood.rb
class Hood < ActiveRecord::Base
  attr_accessible :name
  belongs_to :city
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  attr_accessible :description, :title
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def city
    c = City.find_by_name(params[:city])
    @city_description = c.description
    @city_name = c.name
    @neighborhood_list = c.hoods
    @groups_of_num = @neighborhood_list.count / 3
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @neighborhoods }
    end
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
    @neighborhood = Neighborhood.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @neighborhood }
    end
  end

  # GET /neighborhoods/new
  # GET /neighborhoods/new.json
  def new
    @neighborhood = Neighborhood.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @neighborhood }
    end
  end

  # GET /neighborhoods/1/edit
  def edit
    @neighborhood = Neighborhood.find(params[:id])
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(params[:neighborhood])

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render json: @neighborhood, status: :created, location: @neighborhood }
      else
        format.html { render action: "new" }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /neighborhoods/1
  # PUT /neighborhoods/1.json
  def update
    @neighborhood = Neighborhood.find(params[:id])

    respond_to do |format|
      if @neighborhood.update_attributes(params[:neighborhood])
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood = Neighborhood.find(params[:id])
    @neighborhood.destroy

    respond_to do |format|
      format.html { redirect_to neighborhoods_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us  
  end

  def blog
  end

  def contact
  end

  def elements
  end

  def gallery
  end

  def home_alternative
  end

  def index
  end

  def page_alternative
  end

  def portfolio
  end

  def portfolio_item
  end

  def portfolio_item_2
  end

  def services
  end

  def single_post
  end

  def register
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(page_names, type = :action)
    "active" if [*page_names].include? params[type]
  end
end

app/helpers/city_helper.rb
module CityHelper
  
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/neighborhooods_helper.rb
module NeighborhooodsHelper
end

app/views/home/index.html.erb
<% content_for(:title) { "clean, multipurpose Ruby-Ready HTML template" } %>

<% content_for(:post_header) do %>
    <section id="slider_wrapper">
      <div id="main_flexslider" class="flexslider">
        <ul class="slides">
          <li class="item" style="background-image: url(<%= asset_path("2.jpg") %>)">
            <div class="container">
              <div class="carousel-caption">
                <h1>a <strong>ruby-ready</strong> theme<br>packed as a gem to help you<br><strong>bootstrap</strong> your <strong>rails application</strong>!</h1>
                <p class="lead inverse">{rails}<strong>strap</strong> is based on the famous <strong><a href="https://wrapbootstrap.com/theme/restart-clean-minimal-business-WB0NPLR53">{re}start theme</a></strong> which relies on<strong> good typography</strong> and <strong>large photography</strong>, serving as a foundation for your creative projects.</p>
              </div>
            </div>
          </li>
          <li class="item" style="background-image: url(<%= asset_path("1.jpg") %>)">
            <div class="container">
              <div class="carousel-caption">
                <h1>makes <strong>real use</strong><br>
                  of the power of <strong>{LESS}</strong> syntax!</h1>

                <p class="lead inverse">{rails}<strong>strap</strong> was built with heavy use of {less} technology,
                  making the life of the web developer easier!</p>
              </div>
            </div>
          </li>
          <li class="item" style="background-image: url(<%= asset_path("3.jpg") %>)">
            <div class="container">
              <div class="carousel-caption">
                <h1 class="inverse"><strong>subtle</strong> animations<br>
                  & a <strong>fresh</strong> collapsing <strong>header effect</strong></h1>

                <p class="lead">if you are looking for
                  <a href="<%= services_path %>"><strong>a bold approach</strong></a> you will love the header
                  effect,<br>
                  but even if you like
                  <a href="<%= page_alternative_path %>"><strong>a more conservative feel</strong></a>, you can always
                  try the boxed alternative!</p>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </section>
<% end %>

<section class="call_to_action">
  <h3>boost your development workflow</h3>
  <h4>and make the web a little bit prettier</h4>
  <a class="btn btn-primary btn-large" href="https://wrapbootstrap.com/theme/rails-strap-ruby-ready-theme-WB00952P7">Buy this Rails theme!</a>
</section>
<section id="features_teasers_wrapper">
  <div class="row">
    <div class="span4 feature_teaser"><img alt="responsive" src="<%= asset_path("responsive.png") %>">

      <h3>Clean, Responsive Design</h3>

      <p>A multipurpose but mainly<strong> business oriented</strong> design, built to serve as a foundation for your
        web projects. Suspendisse nec risus fermentum sapien congue fermentum sed at lorem.</p>
    </div>
    <div class="span4 feature_teaser"><img alt="responsive" src="<%= asset_path("git.png") %>">

      <h3>Based on Twitter Bootstrap</h3>

      <p>The front-end development framework with a <strong>steep learning curve</strong>. It changes the way you
        develop sites. Suspendisse nec risus fermentum sapien congue fermentum sed at lorem.</p>
    </div>
    <div class="span4 feature_teaser"><img alt="responsive" src="<%= asset_path("rubyonrails.png") %>">
      <h3>Packed as a Ruby gem</h3>
      <p>{rails}<strong>strap</strong> comes packed as a gem file to help the Ruby on Rails developer save precious time. The plain HTML version <strong>is also included</strong>. Congue fermentum sed at lorem fermentum sed.</p>
    </div>
  </div>
</section>
<section id="portfolio_teasers_wrapper">
  <h2 class="section_header">Recent Work or Projects from Portfolio</h2>

  <div class="portfolio_strict row">
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/a1.jpg") %>)">
        <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>

          <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut
            fermentum...</p>
        </a></div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>

        <p>artists</p>
      </div>
    </div>
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/t5.jpg") %>)">
        <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>

          <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut
            fermentum...</p>
        </a></div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>

        <p>travel</p>
      </div>
    </div>
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/p3.jpg") %>)">
        <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>

          <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut
            fermentum...</p>
        </a></div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>

        <p>people</p>
      </div>
    </div>
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/t4.jpg") %>)">
        <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>

          <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut
            fermentum...</p>
        </a></div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>

        <p>poetic</p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,300italic' rel='stylesheet' type='text/css'>
  <meta charset="utf-8">
  <title>{rails}strap - <%= yield(:title) %></title>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag "application", :media => "all" %>
  <!--[if IE 7]>
    <%= stylesheet_link_tag "font-awesome-ie7.min" %>
  <![endif]-->
  <!-- Fav and touch icons -->
  <%= javascript_include_tag "rails_strap_modernizer"  %>
  <%= csrf_meta_tags %>
  <%=  yield(:head) %>
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-57x57-precomposed.png">
  <link rel="shortcut icon" href="favicon.png">
</head>
<body class="<%= yield(:body_class) %>">
<header>
  <div class="container">
    <div class="navbar">
      <div class="navbar-inner"> <a class="brand" href="<%= root_path %>">  <img src="<%= asset_path("rails_strap_logo.png") %>" width="90" height="90" alt="optional logo"> <span class="logo_title">{rails}<strong>strap</strong></span> <span class="logo_subtitle">a clean bootstrap theme... on Rails!</span> </a> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="nb_left pull-left"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></span>  <span class="nb_right pull-right">menu</span> </a>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <li class="<%= is_active?(['index', 'home_alternative']) %>"><%= link_to "Home", root_path %></li>
            <li class="<%= is_active?(['about_us', 'page_alternative']) %>"><%= link_to "About Us", about_us_path %></li>
            <li class="<%= is_active?('services') %>"><%= link_to "Services", services_path %></li>
            <li class="<%= is_active?(['portfolio', 'gallery', 'portfolio_item', 'portfolio_item_2']) %>"><%= link_to "Portfolio", portfolio_path %></li>
            <li class="<%= is_active?(['blog', 'single_post']) %>"><%= link_to "Blog", blog_path %></li>
            <li class="<%= is_active?('contact') %>"><%= link_to "Contact", contact_path %></li>
            <li class="dropdown"> <a data-toggle="dropdown" class="dropdown-toggle" href="#">Pages<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Home Alternative", home_alternative_path %></li>
                <li><%= link_to "Page Alternative", page_alternative_path %></li>
                <li><%= link_to "Portfolio Masonry", gallery_path %></li>
                <li><%= link_to "Portfolio Item", portfolio_item_path %></li>
                <li><%= link_to "Portfolio Item II", portfolio_item_2_path %></li>
                <li><%= link_to "Single Post", single_post_path %></li>
                <li><%= link_to "ERROR 404", error_404_path %></li>
                <li>
                  <%= link_to register_path do %>
                      Register or Sign In
                      <span class="label label-important">new</span>
                  <% end %>
                </li>
                <li><%= link_to "Bootstrap Elements", elements_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div id="social_media_wrapper"> <a href="#facebook"><i class="icon icon-facebook"></i></a> <a href="#twitter"><i class="icon icon-twitter"></i></a> <a href="#googleplus"><i class="icon icon-google-plus"></i></a> </div>
    <div id="sign">
      <%= link_to register_path do %>
          <i class="icon icon-user"></i>Register/Sign in
      <% end %>
    </div>
  </div>
</header>
<%= yield(:post_header) %>
<div id="main">
  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <%= yield(:neighborhood_list) %>
    <section id="twitter_feed_wrapper">
      <div class="container">
        <div class="row">
          <div class="span1 twitter_feed_icon"><a href="#twitter"><i class="icon icon-twitter-sign"></i></a></div>
          <div class="span11">
            <blockquote>
              <p>Wordle creates Typographic images from any txt or even your delicious bookmarks. Here is my untitled from Anonymous <a href="#">http://unhub.com/LIot</a></p>
              &mdash; LeonART (@leonartgr) <a href="https://twitter.com/leonartgr/">January 25, 2013</a></blockquote>
          </div>
        </div>
      </div>
    </section>
    <section id="footer_teasers_wrapper">
      <div class="container">
        <div class="row">
          <div class="span4 footer_teaser">
            <h3>About us</h3>
            <p>Fugiat dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum mas justo sitters.</p>
            <p><i class="icon-map-marker"></i> 3 Athens street</p>
            <p><i class="icon-phone"></i> (+30) 265-9987</p>
            <p><i class="icon-print"></i> (+30) 9854-7855</p>
            <p><i class="icon-envelope"></i> hello@railsstraptheme.com</p>
          </div>
          <div class="span4 footer_teaser">
            <h3>Latest News</h3>
            <ul class="media-list">
              <li class="media"> <a href="#" class="media-photo" style="background-image:url(<%= asset_path("portfolio/t5.jpg") %>)"></a> <a href="#"  class="media-date">19<span>FEB</span></a>
                <h5 class="media-heading"><a href="#">Media heading, this is a title of a news...</a></h5>
                <p>Fugiat dapibus, tellus ac cursus commodo, ut fermentum...</p>
              </li>
              <li class="media"> <a href="#" class="media-photo" style="background-image:url(<%= asset_path("portfolio/t4.jpg") %>)"></a> <a href="#"  class="media-date">18<span>FEB</span></a>
                <h5 class="media-heading"><a href="#">Media heading, of a news item.</a></h5>
                <p>Fugiat dapibus, tellus ac cursus commodo, condime ntum nibh, ut fermentum...</p>
              </li>
            </ul>
          </div>
          <div class="span4 footer_teaser" id="latest-flickr-images">
            <h3>FlickrFeed</h3>
            <p>All photos &copy; by <a href="http://www.dimitragiannouka.com" target="_blank">Dimitra Giannouka</a>.</p>
            <ul>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <section id="copyright">
      <div class="container">
        <div class="row">
          <div class="span6"> Copyright &copy;2013 all rights reserved </div>
          <div class="span6 text-right">
            Designed by <a href="http://www.leonart.gr">leonart</a>
            & developed by <a href="http://wintersolutions.de">wintersolutions</a>
          </div>
        </div>
      </div>
    </section>
  </footer>
</div>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/pages/gallery.html.erb
<% content_for(:title) {"Gallery"} %>

<div class="hgroup">
  <h1>Masonry portfolio <small>or</small> photo gallery</h1>
  <h2>This is a mixture of portfolio items and photo gallery! We are using the Isotope Jquery plugin to filter results and Prettyphoto to open the lighbox.
    This is the<strong> Masonry Version</strong>, you should also check out the <a href="<%= portfolio_path %>"><strong>strict version</strong></a>. All photos &copy; by <a href="http://www.dimitragiannouka.com" target="_blank">Dimitra Giannouka</a>.</h2>
  <ul class="breadcrumb pull-right">
    <li><a href="<%= root_path %>">Home</a> <span class="divider">/</span></li>
    <li class="active">Portfolio</li>
  </ul>
</div>
<ul id="portfolio_filters">
  <li><a href="#" data-filter="*">show all</a></li>
  <li><a href="#" data-filter=".cat_just_photos">just photos</a></li>
  <li><a href="#" data-filter=".cat_projects">whole projects</a></li>
</ul>
<div id="portfolio_container" class="portfolio_masonry row">
  <div class="portfolio_item cat_just_photos span4"> <a rel='prettyPhoto' href="<%= asset_path("portfolio/t2.jpg") %>"> <img src="<%= asset_path("portfolio/t2.jpg") %>" alt="The title of the photo">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-resize-full"></i> </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_projects span4"> <a href="<%= portfolio_item_path %>"> <img src="<%= asset_path("portfolio/a6.jpg") %>" alt="Title of the project">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-external-link"></i>
        <h3>Title of the project</h3>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_just_photos span4"> <a rel='prettyPhoto' href="<%= asset_path("portfolio/b3.jpg") %>"> <img src="<%= asset_path("portfolio/b3.jpg") %>" alt="The title of the photo">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-resize-full"></i> </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_projects span4"> <a href="<%= portfolio_item_path %>"> <img src="<%= asset_path("portfolio/a4.jpg") %>" alt="Title of the project">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-external-link"></i>
        <h3>Title of the project</h3>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_just_photos span4"> <a rel='prettyPhoto' href="<%= asset_path("portfolio/p4.jpg") %>"> <img src="<%= asset_path("portfolio/p4.jpg") %>" alt="The title of the photo">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-resize-full"></i> </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_projects span4"> <a href="<%= portfolio_item_path %>"> <img src="<%= asset_path("portfolio/t4.jpg") %>" alt="Title of the project">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-external-link"></i>
        <h3>Title of the project</h3>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_just_photos span4"> <a rel='prettyPhoto' href="<%= asset_path("portfolio/t3.jpg") %>"> <img src="<%= asset_path("portfolio/t3.jpg") %>" alt="The title of the photo">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-resize-full"></i> </div>
    </div>
  </a> </div>
  <div class="portfolio_item cat_projects span4"> <a href="<%= portfolio_item_path %>"> <img src="<%= asset_path("portfolio/a3.jpg") %>" alt="Title of the project">
    <div class="overlay">
      <div class="desc"> <i class="icon-2x icon-external-link"></i>
        <h3>Title of the project</h3>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </div>
    </div>
  </a>
  </div>
</div>

app/views/pages/home_alternative.html.erb
<% content_for(:title) { "clean, multipurpose Ruby-Ready HTML template" } %>
<% content_for(:body_class) {"boxed"} %>

<% content_for(:post_header) do %>
    <section id="slider_wrapper" class="container">
      <div id="main_flexslider" class="flexslider">
        <ul class="slides">
          <li class="item"  style="background-image: url(<%= asset_path("s1.jpg") %>)">
            <div class="container">
              <div class="carousel-caption">
                <h1>a <strong>flexible</strong> theme<br>
                  you can <strong>trust</strong> & <strong>build upon</strong>!</h1>
                <p class="lead">based on <strong>good typography</strong> and <strong>large photography</strong>, serving as a foundation for your creative projects. Feel free to browse its templates and discover its features.</p>
              </div>
            </div>
          </li>
          <li class="item"  style="background-image: url(<%= asset_path("s2.jpg") %>)">
            <div class="container">
              <div class="carousel-caption">
                <h1>makes <strong>real use</strong><br>
                  of the power of <strong>{LESS}</strong> syntax!</h1>
                <p class="lead inverse">built with heavy use of {less} technology, making the life of the web developer easier!</p>
              </div>
            </div>
          </li>
          <li class="item"  style="background-image: url(<%= asset_path("s3.jpg") %>)">
            <div class="container">
              <div class="carousel-caption">
                <h1 class="inverse"><strong>subtle</strong> animations<br>
                  & a fresh collapsing <strong>header effect</strong></h1>
                <p class="lead">if you are looking for <a href="<%= services_path %>"><strong>a bold approach</strong></a> you will love the header effect,<br>
                  but even if you like <a href="<%= page_alternative_path %>"><strong>a more conservative feel</strong></a>, you can always try the boxed alternative!</p>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </section>
<% end %>

<section id="features_teasers_wrapper">
  <div class="row">
    <div class="span4 feature_teaser"> <img alt="responsive" src=<%= asset_path("responsive.png") %>>
      <h3>Clean, Responsive Design</h3>
      <p>A multipurpose but mainly<strong> business oriented</strong> design, built to serve as a foundation for your web projects. Suspendisse nec risus fermentum sapien congue fermentum sed at lorem.</p>
    </div>
    <div class="span4 feature_teaser"> <img alt="responsive" src=<%= asset_path("git.png") %>>
      <h3>Based on Twitter Bootstrap</h3>
      <p>The front-end development framework with a <strong>steep learning curve</strong>. It changes the way you develop sites. Suspendisse nec risus fermentum sapien congue fermentum sed at lorem.</p>
    </div>
    <div class="span4 feature_teaser"> <img alt="responsive" src=<%= asset_path("rubyonrails.png") %>>
      <h3>Packed as a Ruby gem</h3>
      <p>{rails}<strong>strap</strong> comes packed as a gem file to help the Ruby on Rails developer save precious time. The plain HTML version <strong>is also included</strong>. Congue fermentum sed at lorem fermentum sed.</p>
    </div>
  </div>
</section>
<section id="portfolio_teasers_wrapper">
  <h2 class="section_header">Recent Work or Projects from Portfolio</h2>
  <div class="portfolio_strict row">
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/a1.jpg") %>)"> <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </a> </div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>
        <p>artists</p>
      </div>
    </div>
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/t5.jpg") %>)"> <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </a> </div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>
        <p>travel</p>
      </div>
    </div>
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/p3.jpg") %>)"> <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </a> </div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>
        <p>people</p>
      </div>
    </div>
    <div class="portfolio_item span3">
      <div class="portfolio_photo" style="background-image:url(<%= asset_path("portfolio/t4.jpg") %>)"> <a href="<%= portfolio_item_path %>"> <i class="icon-2x icon-external-link"></i>
        <p>Description of the project dapibus, tellus ac cursus commodo, mauesris condime ntum nibh, ut fermentum...</p>
      </a> </div>
      <div class="portfolio_description">
        <h3><a href="<%= portfolio_item_path %>">Lorem Ipsum</a></h3>
        <p>poetic</p>
      </div>
    </div>
  </div>
</section>